services:
  # Keycloak Service
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-server
    environment:
      # Admin credentials
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Database (using built-in H2 for development)
      KC_DB: dev-file

      # Hostname settings
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
    ports:
      - "8080:8080"
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - keycloak-network

volumes:
  keycloak_data:
    driver: local

networks:
  keycloak-network:
    driver: bridge
